#!/usr/bin/python3
# script to install and configure HAProxy on lb-01 server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
# Make sure that your servers are configured with the right hostnames
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend isaac-frontend
        bind *:80
        mode http
        default_backend isaac-backend
backend isaac-backend
        balance roundrobin
        server 249734-web-01 100.25.19.204:80 check
        server 249734-web-02 54.157.159.85:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
