#!/usr/bin/env bash
#Bash script that displays content of the current directory
#In a list format, where only the part of the name after the first dash is
#displayed

mylist=$(ls)

for x in $mylist; do
  echo "$x" | cut -d '-' -f2
done
