#!/usr/bin/env bash
# installation and configuration of ufw firewall so that it blocks all incoming
# traffic, except the following TCP ports:22 (SSH), 443 (HTTPS SSL), 80 (HTTP)

sudo apt-get install ufw
sudo ufw status
sudo ufw enable -y
sudo ufw default allow outgoing -y
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
